### ISSUE TITLE
README with icons without background

### ISSUE THREAD

**Issue by cpmachado** [adamshostack/DFD3#4]
Hello there,

I normally use dark theme, and I think many won't be different.
The use of black arrows, without background, makes them invisible.

If you want, I can submit a PR to fix that.

Best regards,
cpmachado

**Comment by adamshostack** [comment]
Sure, thanks!

**Comment by cpmachado** [comment]
PR submitted.
Thank you for your "World's shortest Threat Modeling Course", really enjoyed it.
Have recommended it to all my friends.

**Comment by cpmachado** [comment]
Thanks, will close this then
